# Generated by Django 5.0 on 2024-01-03 17:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='is_coming',
            new_name='ticketChecked',
        ),
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(default=api.models.generate_event_code, max_length=8, unique=True),
        ),
    ]
