# Generated by Django 5.0 on 2024-01-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_is_coming_guest_ticketchecked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
